[functions]
directory = "netlify/functions"

[build]
publish = "."
publishOrigin = "default"
functions = "netlify/functions"

# Disable secrets scanning or exclude certain paths
[build.environment]
SECRETS_SCAN_ENABLED = "false"
NETLIFY_IDENTITY_WIDGET_VERSION = "1"
REACT_APP_NETLIFY_IDENTITY_URL = "/.netlify/identity"


# Plugin configuratie voor Identity styling - DISABLED TO REMOVE LOGIN POPUP
# [[plugins]]
# package = "@netlify/plugin-identity"

# Identity widget custom styling
[context.production.environment]
NETLIFY_WIDGET_THEME = "custom"
NETLIFY_WIDGET_PRIMARY_COLOR = "#14b8a6"
NETLIFY_WIDGET_BACKGROUND = "#ffffff"
NETLIFY_WIDGET_BORDER_RADIUS = "24px"
NETLIFY_WIDGET_FONT_FAMILY = "Plus Jakarta Sans"

[context.deploy-preview.environment]
NETLIFY_WIDGET_THEME = "custom"
NETLIFY_WIDGET_PRIMARY_COLOR = "#14b8a6"
NETLIFY_WIDGET_BACKGROUND = "#ffffff"
NETLIFY_WIDGET_BORDER_RADIUS = "24px"
NETLIFY_WIDGET_FONT_FAMILY = "Plus Jakarta Sans"

# Identity templates configuratie
[identity]
[identity.settings]
enable_signup = true

[identity.templates]
[identity.templates.login]
title = "Narrin AI - Inloggen"
css = """
  :root {
    --primary: #14b8a6;
    --secondary: #f97316;
  }
  body { 
    font-family: 'Plus Jakarta Sans', sans-serif !important; 
  }
  .modal { 
    border-radius: 16px !important; 
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25) !important;
  }
  .btn-primary { 
    background: var(--primary) !important; 
    border-radius: 12px !important;
  }
  input {
    border-radius: 12px !important;
    border: 2px solid #e5e7eb !important;
  }
  input:focus {
    border-color: var(--primary) !important;
    box-shadow: 0 0 0 3px rgba(20, 184, 166, 0.1) !important;
  }
"""

[identity.templates.signup]
title = "Narrin AI - Registreren"
css = """
  :root {
    --primary: #14b8a6;
    --secondary: #f97316;
  }
  body { 
    font-family: 'Plus Jakarta Sans', sans-serif !important; 
  }
  .modal { 
    border-radius: 16px !important; 
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25) !important;
  }
  .btn-primary { 
    background: var(--primary) !important; 
    border-radius: 12px !important;
  }
  input {
    border-radius: 12px !important;
    border: 2px solid #e5e7eb !important;
  }
  input:focus {
    border-color: var(--primary) !important;
    box-shadow: 0 0 0 3px rgba(20, 184, 166, 0.1) !important;
  }
"""