plugins = []
headers = []
redirects = []

[functions]
directory = "netlify/functions"

[functions."*"]

[build]
publish = "."
publishOrigin = "default"
functions = "netlify/functions"

[build.environment]
NETLIFY_IDENTITY_WIDGET_VERSION = "1"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

# Plugin configuratie voor Identity styling
[[plugins]]
package = "@netlify/plugin-identity"

# Identity widget custom styling
[context.production.environment]
NETLIFY_WIDGET_THEME = "custom"
NETLIFY_WIDGET_PRIMARY_COLOR = "#14b8a6"
NETLIFY_WIDGET_BACKGROUND = "#ffffff"
NETLIFY_WIDGET_BORDER_RADIUS = "24px"
NETLIFY_WIDGET_FONT_FAMILY = "Plus Jakarta Sans"

[context.deploy-preview.environment]
NETLIFY_WIDGET_THEME = "custom"
NETLIFY_WIDGET_PRIMARY_COLOR = "#14b8a6"
NETLIFY_WIDGET_BACKGROUND = "#ffffff"
NETLIFY_WIDGET_BORDER_RADIUS = "24px"
NETLIFY_WIDGET_FONT_FAMILY = "Plus Jakarta Sans"