POST https://hook.eu2.make.com/lya166veex7oo2wwo8mx4fuhlkssxlog
Content-Type: application/json

{
  "user_email": "smitssebastiaan2+2@gmail.com",
  "user_uid": "0f5dda13-50b7-462c-bd5-d14f0258cd02",
  "user_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDkyNDYyMDQsInN1YiI6IjBmNWRkYTEzLTUwYjctNDYyYy1iZDVkLWQxNGYwMjU4Y2QwMiIsImVtYWlsIjoic21pdHNzZWJhc3RpYWFuMisyQGdtYWlsLmNvbSIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIn0sInVzZXJfbWV0YWRhdGEiOnsiZnVsbF9uYW1lIjoiV2lsbHkgV2Fua2EifX0.6B8GEmNteZfjV_UK90OGT5AWoLmF6NGb066OHoLhPUw",
  "action": "update",
  "field": "email", 
  "value": "nieuw-email@example.com"
}
