curl -X POST https://hook.eu2.make.com/03ug6qzucda4ksrkcc06nu3bu3vetj15 \
    -H "Content-Type: application/json" \
    -d '{
      "event": "validate",
      "instance_id": "f340b46d-f894-4617-95fc-71173fced23d",
      "user": {
        "id": "test-user-12345678-1234-1234-1234-123456789012",
        "aud": "",
        "role": "",
        "email": "testuser@example.com",
        "app_metadata": {
          "provider": "email"
        },
        "user_metadata": {
          "full_name": "Test User"
        },
        "created_at": "2025-08-01T16:00:00.000000Z",
        "updated_at": "2025-08-01T16:00:00.000000Z"
      }
    }'